### ISSUE TITLE
important : true is not suppurted

### ISSUE THREAD

**Issue by danielt69** [tailwindlabs/tailwindcss-custom-forms#78] opened 2020-10-21 22:40 UTC
Hi there, When I use this plugin while I setup **important : true** in tailwind.config.js setting file, all styles are with suffix !important but the styles from this plugin.

I hope it's clear.

![image](https://user-images.githubusercontent.com/3322065/96794819-8eeaa100-1407-11eb-8a29-b7fa37435a36.png)

**Comment by adamwathan** [comment] 2020-11-11 16:11
The important option only applies to utility classes, not to component classes. Happy to help you come up with a solution to your problem another way but going to close this as intended behavior.

**Closed by adamwathan** 2020-11-11 16:11 UTC
